export const LOAD_POKEMONS_LOADING = 'LOAD_POKEMONS_LOADING';
export const LOAD_POKEMONS_SUCCESS = 'LOAD_POKEMONS_SUCCESS';
export const LOAD_POKEMONS_ERROR = 'LOAD_POKEMONS_ERROR';
export const LOAD_POKEMON_DETAIL_LOADING = 'LOAD_POKEMON_DETAIL_LOADING';
export const LOAD_POKEMON_DETAIL_SUCCESS = 'LOAD_POKEMON_DETAIL_SUCCESS';
export const LOAD_POKEMON_DETAIL_ERROR = 'LOAD_POKEMON_DETAIL_ERROR';